#!/bin/sh

clock() {
	date '+%a, %e %b %H:%M %Z'
}

battery0() {
	BAT0C=/sys/class/power_supply/BAT0/capacity
	BAT0S=/sys/class/power_supply/BAT0/status

	test "`cat $BAT0S`" = "Unknown" && echo 'Idle' || sed -n p $BAT0S
	sed -n p $BAT0C
}

battery1() {
	BAT1C=/sys/class/power_supply/BAT1/capacity
	BAT1S=/sys/class/power_supply/BAT1/status

	test "`cat $BAT1S`" = "Unknown" && echo 'Idle' || sed -n p $BAT1S
	sed -n p $BAT1C
}

desktop() {
	DESK=`xprop -root _NET_CURRENT_DESKTOP | awk '{print $3}'`
	echo $((DESK+1))
}

volume() {
	amixer -D pulse get Master | grep 'Front Left: Playback' | grep -o '...%' | sed 's/\[//' | sed 's/%//' | sed 's/ //'
}

# Handle output with buffers
while :; do
	buf=" "
	buf="${buf} %{F#2F343F}%{B#2F343F} "
	buf="${buf} %{l}%{F#D3DAE3}%{T-} Desktop $(desktop) "
	buf="${buf} %{c} $(clock) "
	buf="${buf} %{r} VOL: $(volume)% "
	buf="${buf} BA0: $(battery0)% "
	buf="${buf} BA1: $(battery1)%  "
	buf="${buf} %{F#2F343F} "

	echo $buf
	sleep 1
done |
lemonbar -p -f DroidSans-10 -g 1342x30+12+12 -u 2 -U #2F343F | bash
