#! /bin/sh

sxhkd &

bspc monitor -d I II III IV V VI VII VIII IX X

bspc config border_width         0
bspc config window_gap          24
bspc config bottom_padding 	32

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config focus_by_distance    true
bspc config history_aware_focus  true

bspc config normal_border_color "#7B7C82"
bspc config focused_border_color "#00BCD4"

bspc rule -a Gimp state=floating follow=on
bspc rule -a Chromium desktop='^2'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a wicd-gtk state=floating

compton -bfc -G -m 1.0 -D 3 --inactive-dim 0.1
pulseaudio &
rofi &
~/.bin/bar &
~/.fehbg &
